# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALToxqeOTByHk8DvzcZdUN8Y7-OToF8n
"""

!pip install -q ultralytics roboflow

import ultralytics
ultralytics.checks()

from google.colab import userdata
from roboflow import Roboflow

api_key = userdata.get("ROBOFLOW_API_KEY")

rf = Roboflow(api_key=api_key)
project = rf.workspace("novalrizkiansyah-ymail-com").project("aksara-ulu-rejang")
dataset = project.version(4).download("yolov8")

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=200,
    imgsz=640,
    batch=16,
    patience=20,
    name="kaganga_yolo11n"
)

from ultralytics import YOLO
from IPython.display import Image, display
import os

model = YOLO("/content/runs/detect/kaganga_yolo11n/weights/best.pt")

metrics = model.val(
    data=f"{dataset.location}/data.yaml",
    split="test",
    imgsz=640,
    conf=0.25,
    iou=0.5,
    plots=True,
    name="kaganga_yolo11n_test"
)

result_dir = "/content/runs/detect/kaganga_yolo11n"

display(Image(filename=os.path.join(result_dir, "confusion_matrix.png"), width=900))

display(Image(filename=os.path.join(result_dir, "confusion_matrix_normalized.png"), width=900))

print("mAP50-95:", metrics.box.map)
print("mAP50:", metrics.box.map50)
print("mAP75:", metrics.box.map75)
print("Precision:", metrics.box.mp)
print("Recall:", metrics.box.mr)

model.predict(
    source=f"{dataset.location}/test/images",
    conf=0.25,
    save=True
)

import glob
from IPython.display import Image, display

hasil = glob.glob("/content/runs/detect/predict/*.jpg")
display(Image(filename=hasil[0]))

from IPython.display import Image, display
import glob

predicted_images = glob.glob("/content/runs/detect/predict*/*.jpg")

for img_path in predicted_images[-5:]:
    display(Image(filename=img_path, width=500))







